--SELECT *
--FROM ALL_CONS_COLUMNS
--WHERE OWNER  ='ISIS2304A03202120';

--Para borrar todo
--DROP TABLE ACCIONES CASCADE CONSTRAINTS;
--DROP TABLE CAJEROS CASCADE CONSTRAINTS;
--DROP TABLE CAJEROSAUTOMATICOS CASCADE CONSTRAINTS;
--DROP TABLE CLIENTES CASCADE CONSTRAINTS;
--DROP TABLE CLIENTESPRODUCTOS CASCADE CONSTRAINTS;
--DROP TABLE CUENTAS CASCADE CONSTRAINTS;
--DROP TABLE DEPOSITOSINVERSION CASCADE CONSTRAINTS;
--DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;
--DROP TABLE GERENTEGENERAL CASCADE CONSTRAINTS; 
--DROP TABLE GERENTESDEOFICINA CASCADE CONSTRAINTS;
--DROP TABLE OFICINAS CASCADE CONSTRAINTS;
--DROP TABLE OPERACIONESBANCARIAS CASCADE CONSTRAINTS;
--DROP TABLE PRESTAMOS CASCADE CONSTRAINTS;
--DROP TABLE PRODUCTOS CASCADE CONSTRAINTS;
--DROP TABLE PUESTOSATENCIONOFICINA CASCADE CONSTRAINTS;
--DROP TABLE PUESTOSATENCIONTIPOSOPERACION CASCADE CONSTRAINTS;
--DROP TABLE PUESTOSDEATENCION CASCADE CONSTRAINTS;
--DROP TABLE PUESTOSDIGITALES CASCADE CONSTRAINTS;
--DROP TABLE TIPOSOPERACION CASCADE CONSTRAINTS;
--DROP TABLE USUARIOS CASCADE CONSTRAINTS;
--DROP TABLE USUARIOSTIPOSOPERACION CASCADE CONSTRAINTS;
--DROP SEQUENCE BANCANDES_SEQUENCE;
--DROP TABLE ASOCIACIONES CASCADE CONSTRAINTS;
--DROP TABLE ASOCIACIONCUENTASEMPLEADOS CASCADE CONSTRAINTS;


--Creacion del secuenciador
CREATE SEQUENCE BANCANDES_SEQUENCE;

-- Creacion tabla USUARIOS y restricciones
CREATE TABLE USUARIOS
(
    LOGIN VARCHAR2(20) PRIMARY KEY
);


-- Creacion tabla EMPLEADOS y restricciones
CREATE TABLE EMPLEADOS
(
    LOGIN VARCHAR2(20) PRIMARY KEY
);


    
-- Creacion tabla TIPOSOPERACION y restricciones
CREATE TABLE TIPOSOPERACION
(
    TIPO VARCHAR2(30) PRIMARY KEY
);


    
-- Creacion tabla PRODUCTOS y restricciones
CREATE TABLE PRODUCTOS
(
    ID NUMBER PRIMARY KEY 
);


-- Creacion tabla puesto de atencion y restricciones
CREATE TABLE PUESTOSDEATENCION
(
    ID NUMBER PRIMARY KEY 
);


-- Creacion tabla CLIENTES y restricciones
CREATE TABLE CLIENTES
(
    TIPODOCUMENTO VARCHAR2(18) NOT NULL,
    NUMERODOCUMENTO NUMBER NOT NULL,
    DEPARTAMENTO VARCHAR2(30) NOT NULL,
    CODIGOPOSTAL NUMBER NOT NULL,
    NACIONALIDAD VARCHAR2(30) NOT NULL, 
    NOMBRE VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    LOGIN VARCHAR2(20) PRIMARY KEY,
    CONTRASENA VARCHAR2(30),
    CORREO VARCHAR2(50),
    TELEFONO INTEGER,
    CIUDAD VARCHAR2(30),
    TIPO VARCHAR2(17) NOT NULL    
);

-- Creacion tabla CAJEROS y restricciones
CREATE TABLE CAJEROS
(
    TIPODOCUMENTO VARCHAR2(20),
    NUMERODOCUMENTO NUMBER NOT NULL,
    DEPARTAMENTO VARCHAR2(30) NOT NULL,
    CODIGOPOSTAL NUMBER NOT NULL,
    NACIONALIDAD VARCHAR2(30) NOT NULL, 
    NOMBRE VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    LOGIN VARCHAR2(20) PRIMARY KEY,
    CONTRASENA VARCHAR2(30),
    CORREO VARCHAR2(50),
    TELEFONO INTEGER,
    CIUDAD VARCHAR2(30),
    ADMINISTRADOR VARCHAR2(10) NOT NULL,
    PUESTOATENCIONOFICINA NUMBER,
    OFICINA NUMBER

); 
   
   
-- Creacion tabla gerente de OFICINAS y restricciones
CREATE TABLE GERENTESDEOFICINA
(
    TIPODOCUMENTO VARCHAR2(20),
    NUMERODOCUMENTO NUMBER NOT NULL,
    DEPARTAMENTO VARCHAR2(30) NOT NULL,
    CODIGOPOSTAL NUMBER NOT NULL,
    NACIONALIDAD VARCHAR2(30) NOT NULL, 
    NOMBRE VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    LOGIN VARCHAR2(20) PRIMARY KEY,
    CONTRASENA VARCHAR2(30),
    CORREO VARCHAR2(50),
    TELEFONO INTEGER,
    CIUDAD VARCHAR2(30),
    ADMINISTRADOR VARCHAR2(10) NOT NULL

);

-- Creacion tabla gerente general y restricciones
CREATE TABLE GERENTEGENERAL
(
    TIPODOCUMENTO VARCHAR2(20),
    NUMERODOCUMENTO NUMBER NOT NULL,
    DEPARTAMENTO VARCHAR2(30) NOT NULL,
    CODIGOPOSTAL NUMBER NOT NULL,
    NACIONALIDAD VARCHAR2(30) NOT NULL, 
    NOMBRE VARCHAR2(50) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    LOGIN VARCHAR2(20) PRIMARY KEY,
    CONTRASENA VARCHAR2(30),
    CORREO VARCHAR2(50),
    TELEFONO INTEGER,
    CIUDAD VARCHAR2(30),
    ADMINISTRADOR VARCHAR2(10) NOT NULL,
    OFICINA NUMBER

);

-- Creacion tabla OFICINAS y restricciones
CREATE TABLE OFICINAS
(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
    DIRECCION VARCHAR2(50) NOT NULL UNIQUE,
    PUESTOSPOSIBLES NUMBER NOT NULL,
    GERENTELOGIN VARCHAR(20) NOT NULL
    
);
      
    
-- Creacion tabla puesto atencion OFICINAS y restricciones
CREATE TABLE PUESTOSATENCIONOFICINA
(
    ID NUMBER PRIMARY KEY,
    TELEFONO NUMBER UNIQUE,
    LOCALIZACION VARCHAR2(20) NOT NULL, 
    OFICINA NUMBER
);

  
-- Creacion tabla puesto digital y restricciones
CREATE TABLE PUESTOSDIGITALES
(
    ID NUMBER PRIMARY KEY,
    TELEFONO INTEGER UNIQUE,
    TIPO VARCHAR2(12) NOT NULL,
    URL VARCHAR2(50) UNIQUE
);


-- Creacion tabla CAJEROS automatico y restricciones
CREATE TABLE CAJEROSAUTOMATICOS
(
    ID NUMBER PRIMARY KEY,
    TELEFONO INTEGER UNIQUE,
    LOCALIZACION VARCHAR2(30) NOT NULL
);

-- Creacion tabla operacion bancaria y restricciones
CREATE TABLE OPERACIONESBANCARIAS
(
    ID NUMBER PRIMARY KEY,
    VALOR NUMBER,
    FECHA DATE NOT NULL,
    CLIENTE VARCHAR2(20) NOT NULL,
    PRODUCTOORIGEN NUMBER NOT NULL,
    PRODUCTODESTINO NUMBER DEFAULT NULL, 
    TIPOOPERACION VARCHAR2(30)NOT NULL,
    PUESTOATENCION NUMBER NOT NULL,
    EMPLEADO VARCHAR2(20) DEFAULT NULL
);

-- Creacion tabla asociacion
CREATE TABLE ASOCIACIONES
(
    ID NUMBER PRIMARY KEY,
    VALOR NUMBER,
    FRECUENCIA VARCHAR2(10),
    CUENTACORPORATIVO NUMBER NOT NULL UNIQUE
);

       
-- Creacion tabla PRESTAMOS y restricciones
CREATE TABLE PRESTAMOS
(
    ID NUMBER PRIMARY KEY,
    MONTO NUMBER NOT NULL,
    SALDOPENDIENTE NUMBER NOT NULL,
    INTERES NUMBER NOT NULL,
    NUMEROCUOTAS NUMBER NOT NULL,
    DIAPAGO NUMBER(2,0) NOT NULL,
    VALORCUOTAMINIMA NUMBER NOT NULL,
    FECHAPRESTAMO DATE NOT NULL,
    CERRADO VARCHAR2(10) NOT NULL,
    OFICINA NUMBER NOT NULL
);
 
-- Creacion tabla CUENTAS y restricciones
CREATE TABLE CUENTAS
(
    ID NUMBER PRIMARY KEY,
    NUMEROCUENTA INTEGER UNIQUE NOT NULL,
    ESTADO VARCHAR2(15) NOT NULL,
    TIPO VARCHAR2(15) NOT NULL,
    SALDO NUMBER NOT NULL,
    FECHACREACION DATE NOT NULL,
    FECHAVENCIMIENTO DATE DEFAULT NULL, 
    TASARENDIMIENTO NUMBER NOT NULL,
    OFICINA NUMBER NOT NULL,
    CORPORATIVO VARCHAR2(10) NOT NULL
    
);
   
    
-- Creacion tabla ACCIONES y restricciones
CREATE TABLE ACCIONES
(
    ID NUMBER PRIMARY KEY,
    PRECIO NUMBER NOT NULL,
    DIVIDENDO NUMBER NOT NULL,
    EMPRESA VARCHAR2(30) NOT NULL
);

-- Creacion tabla deposito inversion y restricciones
CREATE TABLE DEPOSITOSINVERSION
(
    ID NUMBER PRIMARY KEY,
    MONTO NUMBER NOT NULL,
    TASARENDIMIENTO NUMBER NOT NULL,
    RIESGO VARCHAR2(7) NOT NULL,
    FECHAINVERSION DATE NOT NULL
    
);
  
-- Creacion tabla USUARIOS tipo operacion y restricciones
CREATE TABLE USUARIOSTIPOSOPERACION
(
    TIPOOPERACION VARCHAR2(30), 
    USUARIO VARCHAR2(20),
    CONSTRAINT PK_USUARIOSTIPOSOPERACION PRIMARY KEY(TIPOOPERACION,USUARIO)
    
);


-- Creacion tabla puesto atencion tipo operacion y restricciones
CREATE TABLE PUESTOSATENCIONTIPOSOPERACION
(
    TIPOOPERACION VARCHAR2(30),
    PUESTOATENCION NUMBER,
    CONSTRAINT PK_PUESTOSATENCIONTIPOSOPERACION PRIMARY KEY(TIPOOPERACION,PUESTOATENCION)
);
     
-- Creacion tabla CLIENTES productos y restricciones
CREATE TABLE CLIENTESPRODUCTOS
(
    PRODUCTO NUMBER,
    CLIENTE VARCHAR2(20),
    CONSTRAINT PK_CLIENTESPRODUCTOSPRIMARY PRIMARY KEY(PRODUCTO,CLIENTE)
    
);


-- Creacion tabla Asociacion Cuentas Empleados
CREATE TABLE ASOCIACIONCUENTASEMPLEADOS
(
    ASOCIACION NUMBER,
    CUENTAEMPLEADO NUMBER,
    CONSTRAINT PK_ASOCIACIONCUENTASEMPLEADOSPRIMARY PRIMARY KEY(ASOCIACION,CUENTAEMPLEADO)
    
);



ALTER TABLE USUARIOS

    ADD CONSTRAINT CHK_LENGTHLOGIN_USUARIOS
    CHECK(LENGTH(LOGIN)>5)
    
    ADD CONSTRAINT CHK_SINESPACIOS_USUARIOS
    CHECK(INSTR(LOGIN,' ')=0);


ALTER TABLE EMPLEADOS
    
    ADD CONSTRAINT CHK_LENGTHLOGIN_EMPLEADOS
    CHECK(LENGTH(LOGIN)>5)
    
    ADD CONSTRAINT CHK_SINESPACIOS_EMPLEADOS
    CHECK(INSTR(LOGIN,' ')=0);
    
ALTER TABLE EMPLEADOS
    ADD CONSTRAINT FK_LOGIN_EMPLEADOS
    FOREIGN KEY (LOGIN) REFERENCES USUARIOS(LOGIN);
    
  ALTER TABLE TIPOSOPERACION

    ADD CONSTRAINT CHK_TIPO_TIPOSOPERACION
    CHECK(TIPO IN ('ABRIR','CERRAR','CONSIGNAR','TRANSFERIR','RETIRAR','SOLICITAR', 'APROBAR', 'RENOVAR', 'RECHAZAR','DESACTIVAR','ACTIVAR', 'PAGAR_CUOTA', 'LIQUIDAR_RENDIMIENTOS', 'PAGAR_CUOTA_EXTRAORDINARIA'));
 
    
    ALTER TABLE CLIENTES
    
    ADD CONSTRAINT CHK_NUMERODOCUMENTO_CLIENTES
    CHECK( LENGTH(NUMERODOCUMENTO)>5)
    
    ADD CONSTRAINT CHK_CORREO_CLIENTES
    CHECK( CORREO LIKE '%_@_%')
    
    ADD CONSTRAINT CHK_TIPODOCUMENTO_CLIENTES
    CHECK( TIPODOCUMENTO IN ('NIT','PEP','CEDULA_CIUDADANIA', 'CEDULA_EXTRANJERIA','TARJETA_IDENTIDAD'))
    
    
    ADD CONSTRAINT CHK_CONTRASENA_CLIENTES
    CHECK(LENGTH(CONTRASENA)>8)
    
    ADD CONSTRAINT CHK_TELEFONO_CLIENTES
    CHECK(LENGTH(TELEFONO)>6)
    
    ADD CONSTRAINT CHK_TIPO_CLIENTES
    CHECK( TIPO IN ('PERSONA_NATURAL', 'PERSONA_JURIDICA'));
       
    
    ALTER TABLE CLIENTES   
    ADD CONSTRAINT FK_LOGIN_CLIENTES
    FOREIGN KEY (LOGIN) REFERENCES USUARIOS(LOGIN);
    
    ALTER TABLE CAJEROS
    ADD CONSTRAINT CHK_TIPODOCUMENTO_CAJEROS
    CHECK (TIPODOCUMENTO IN ('PEP','CEDULA_CIUDADANIA', 'CEDULA_EXTRANJERIA'))
    
    ADD CONSTRAINT CHK_NUMERODOCUMENTO_CAJEROS
    CHECK( LENGTH(NUMERODOCUMENTO)>5)
    
    ADD CONSTRAINT CHK_CONTRASENA_CAJEROS
    CHECK(LENGTH(CONTRASENA)>8)
    
    ADD CONSTRAINT CHK_ADMINISTRADOR_CAJEROS
    CHECK(ADMINISTRADOR IN ('TRUE','FALSE'))
    
    ADD CONSTRAINT CHK_CORREO_CAJEROS
    CHECK( CORREO LIKE '%_@_%')
    
    ADD CONSTRAINT CHK_TELEFONO_CAJEROS
    CHECK(LENGTH(TELEFONO)>6);
    
    ALTER TABLE CAJEROS   
    ADD CONSTRAINT FK_LOGIN_CAJEROS
    FOREIGN KEY (LOGIN) REFERENCES EMPLEADOS(LOGIN);
    
    ALTER TABLE CAJEROS   
    ADD CONSTRAINT FK_PUESTOATENCIONOFICINA_CAJEROS
    FOREIGN KEY (PUESTOATENCIONOFICINA) REFERENCES PUESTOSATENCIONOFICINA(ID);
    
    ALTER TABLE CAJEROS   
    ADD CONSTRAINT FK_OFICINA_CAJEROS
    FOREIGN KEY (OFICINA) REFERENCES OFICINAS(ID);
    
    
    
ALTER TABLE GERENTESDEOFICINA
    ADD CONSTRAINT CHK_TIPODOCUMENTO_GERENTESDEOFICINA
    CHECK (TIPODOCUMENTO IN ('PEP','CEDULA_CIUDADANIA', 'CEDULA_EXTRANJERIA'))
    
    ADD CONSTRAINT CHK_NUMERODOCUMENTO_GERENTESDEOFICINA
    CHECK( LENGTH(NUMERODOCUMENTO)>5)
    
    ADD CONSTRAINT CHK_CONTRASENA_GERENTESDEOFICINA
    CHECK(LENGTH(CONTRASENA)>8)
    
    ADD CONSTRAINT CHK_ADMINISTRADOR_GERENTESDEOFICINA
    CHECK(ADMINISTRADOR IN ('TRUE','FALSE'))
    
    ADD CONSTRAINT CHK_CORREO_GERENTESDEOFICINA
    CHECK( CORREO LIKE '%_@_%')
    
    ADD CONSTRAINT CHK_TELEFONO_GERENTESDEOFICINA
    CHECK(LENGTH(TELEFONO)>6);
    
ALTER TABLE GERENTESDEOFICINA   
    ADD CONSTRAINT FK_LOGIN_GERENTESDEOFICINA
    FOREIGN KEY (LOGIN) REFERENCES EMPLEADOS(LOGIN);
    
    
    
ALTER TABLE GERENTEGENERAL
    ADD CONSTRAINT CHK_TIPODOCUMENTO_GERENTEGENERAL
    CHECK (TIPODOCUMENTO IN ('PEP','CEDULA_CIUDADANIA', 'CEDULA_EXTRANJERIA'))
    
    ADD CONSTRAINT CHK_NUMERODOCUMENTO_GERENTEGENERAL
    CHECK( LENGTH(NUMERODOCUMENTO)>5)
    
    ADD CONSTRAINT CHK_CONTRASENA_GERENTEGENERAL
    CHECK(LENGTH(CONTRASENA)>8)
    
    ADD CONSTRAINT CHK_ADMINISTRADOR_GERENTEGENERAL
    CHECK(ADMINISTRADOR IN ('TRUE','FALSE'))
        
    ADD CONSTRAINT CHK_CORREO_GERENTEGENERAL
    CHECK( CORREO LIKE '%_@_%')
    
    ADD CONSTRAINT CHK_TELEFONO_GERENTEGENERAL
    CHECK(LENGTH(TELEFONO)>6);
    
ALTER TABLE GERENTEGENERAL
    ADD CONSTRAINT FK_LOGIN_GERENTEGENERAL
    FOREIGN KEY (LOGIN) REFERENCES EMPLEADOS(LOGIN);
    
ALTER TABLE GERENTEGENERAL  
    ADD CONSTRAINT FK_OFICINA_GERENTEGENERAL
    FOREIGN KEY (OFICINA) REFERENCES OFICINAS(ID);
    
    ALTER TABLE OFICINAS
    
    ADD CONSTRAINT CHK_PUESTOSPOSIBLES_OFICINAS
    CHECK(PUESTOSPOSIBLES>=0);
    
ALTER TABLE OFICINAS  
    ADD CONSTRAINT FK_GERENTELOGIN_OFICINAS
    FOREIGN KEY (GERENTELOGIN) REFERENCES GERENTESDEOFICINA(LOGIN);
    
    ALTER TABLE PUESTOSATENCIONOFICINA
    
    ADD CONSTRAINT CHK_TELEFONO_PUESTOSATENCIONOFICINA
    CHECK(LENGTH(TELEFONO)>6);
    
ALTER TABLE PUESTOSATENCIONOFICINA
    ADD CONSTRAINT FK_ID_PUESTOSATENCIONOFICINA
    FOREIGN KEY (ID) REFERENCES PUESTOSDEATENCION(ID)
    ON DELETE CASCADE;
    
ALTER TABLE PUESTOSATENCIONOFICINA
    ADD CONSTRAINT FK_OFICINA_PUESTOSATENCIONOFICINA
    FOREIGN KEY (OFICINA) REFERENCES OFICINAS(ID);
    
    
    ALTER TABLE PUESTOSDIGITALES
    
    ADD CONSTRAINT CHK_TELEFONO_PUESTOSDIGITALES
    CHECK(LENGTH(TELEFONO)>6)
    
    ADD CONSTRAINT CHK_TIPO_PUESTOSDIGITALES
    CHECK(TIPO IN ('APP', 'PAGINA_WEB'));
    
ALTER TABLE PUESTOSDIGITALES
    ADD CONSTRAINT FK_ID_PUESTOSDIGITALES
    FOREIGN KEY (ID) REFERENCES PUESTOSDEATENCION(ID)
    ON DELETE CASCADE;
    
    
    ALTER TABLE CAJEROSAUTOMATICOS
    
    ADD CONSTRAINT CHK_TELEFONO_CAJEROSAUTOMATICOS
    CHECK(LENGTH(TELEFONO)>6);
    
ALTER TABLE CAJEROSAUTOMATICOS
    ADD CONSTRAINT FK_ID_CAJEROSAUTOMATICOS
    FOREIGN KEY (ID) REFERENCES PUESTOSDEATENCION(ID)
    ON DELETE CASCADE;


ALTER TABLE OPERACIONESBANCARIAS
    ADD CONSTRAINT FK_CLIENTE_OPERACIONESBANCARIAS
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(LOGIN);
    
ALTER TABLE OPERACIONESBANCARIAS
    ADD CONSTRAINT FK_PRODUCTOORIGEN_OPERACIONESBANCARIAS
    FOREIGN KEY (PRODUCTOORIGEN) REFERENCES PRODUCTOS(ID);
    
ALTER TABLE OPERACIONESBANCARIAS
    ADD CONSTRAINT FK_TIPOOPERACION_OPERACIONESBANCARIAS
    FOREIGN KEY (TIPOOPERACION) REFERENCES TIPOSOPERACION(TIPO);
    
ALTER TABLE OPERACIONESBANCARIAS
    ADD CONSTRAINT FK_PUESTOATENCION_OPERACIONESBANCARIAS
    FOREIGN KEY (PUESTOATENCION) REFERENCES PUESTOSDEATENCION(ID);
    
ALTER TABLE OPERACIONESBANCARIAS
    ADD CONSTRAINT FK_EMPLEADO_OPERACIONESBANCARIAS
    FOREIGN KEY (EMPLEADO) REFERENCES EMPLEADOS(LOGIN);
    
ALTER TABLE OPERACIONESBANCARIAS
    ADD CONSTRAINT FK_PRODUCTODESTINO_OPERACIONESBANCARIAS
    FOREIGN KEY (PRODUCTODESTINO) REFERENCES PRODUCTOS(ID);
       
       
       
ALTER TABLE PRESTAMOS
    
    ADD CONSTRAINT CHK_MONTO_PRESTAMOS
    CHECK(LENGTH(MONTO)>0)
    
    ADD CONSTRAINT CHK_SALDOPENDIENTE_PRESTAMOS
    CHECK(LENGTH(SALDOPENDIENTE)>=0)
    
    ADD CONSTRAINT CHK_INTERES_PRESTAMOS
    CHECK(LENGTH(INTERES)>=0)
    
    ADD CONSTRAINT CHK_CERRADO_PRESTAMOS
    CHECK(CERRADO IN ('TRUE','FALSE'))
    
    ADD CONSTRAINT CHK_NUMEROCUOTAS_PRESTAMOS
    CHECK(LENGTH(NUMEROCUOTAS)>=0)
    
    ADD CONSTRAINT CHK_DIAPAGO_PRESTAMOS
    CHECK(DIAPAGO>0 AND DIAPAGO<32)
    
    ADD CONSTRAINT CHK_VALORCUOTAMINIMA_PRESTAMOS
    CHECK(VALORCUOTAMINIMA>=0);
    
ALTER TABLE PRESTAMOS
    ADD CONSTRAINT FK_ID_PRESTAMOS
    FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
     ON DELETE CASCADE;
    
 ALTER TABLE PRESTAMOS
    ADD CONSTRAINT FK_OFICINA_PRESTAMOS
    FOREIGN KEY (OFICINA) REFERENCES OFICINAS(ID);    
    
 ALTER TABLE CUENTAS
    
    ADD CONSTRAINT CHK_NUMEROCUENTA_CUENTAS
    CHECK(LENGTH(NUMEROCUENTA)>4)
    
    ADD CONSTRAINT CHK_SALDO_CUENTAS
    CHECK(LENGTH(SALDO)>=0)
    
    ADD CONSTRAINT CHK_TASARENDIMIENTO_CUENTAS
    CHECK(LENGTH(TASARENDIMIENTO)>=0)
    
    ADD CONSTRAINT CHK_FECHAVENCIMIENTO_CUENTAS
    CHECK(FECHAVENCIMIENTO>FECHACREACION)
    
    ADD CONSTRAINT CHK_ESTADO_CUENTAS
    CHECK(ESTADO IN ('ACTIVA', 'DESACTIVADA', 'CERRADA'))
    
    ADD CONSTRAINT CHK_TIPO_CUENTAS
    CHECK(TIPO IN ('AHORROS','CORRIENTE','AFC', 'CDT'))
    
    ADD CONSTRAINT CHK_CORPORATIVO_CUENTAS
    CHECK(CORPORATIVO IN ('TRUE','FALSE'));
    
ALTER TABLE CUENTAS
    ADD CONSTRAINT FK_ID_CUENTAS
    FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
    ON DELETE CASCADE;
    
ALTER TABLE CUENTAS
    ADD CONSTRAINT FK_OFICINA_CUENTAS
    FOREIGN KEY (OFICINA) REFERENCES OFICINAS(ID);
    
    
    
    ALTER TABLE ACCIONES
    
    ADD CONSTRAINT CHK_DIVIDENDO_ACCIONES
    CHECK(DIVIDENDO>=0)
    
    ADD CONSTRAINT CHK_PRECIO_ACCIONES
    CHECK(PRECIO>=0);
    
   
    
ALTER TABLE ACCIONES
    ADD CONSTRAINT FK_ID_ACCIONES
    FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
     ON DELETE CASCADE;
    
    ALTER TABLE DEPOSITOSINVERSION
    
    ADD CONSTRAINT CHK_MONTO_DEPOSITOSINVERSION
    CHECK(MONTO>=0)
    
    ADD CONSTRAINT CHK_TASARENDIMIENTO_DEPOSITOSINVERSION
    CHECK(TASARENDIMIENTO>=0)
    
    ADD CONSTRAINT CHK_RIESGO_DEPOSITOSINVERSION
    CHECK(RIESGO IN ('BAJO', 'MEDIO', 'ALTO'));
    
    
ALTER TABLE ASOCIACIONES
    ADD CONSTRAINT FK_CUENTACORPORATIVO_ASOCIACIONES
    FOREIGN KEY (CUENTACORPORATIVO) REFERENCES CUENTAS(ID);

ALTER TABLE ASOCIACIONES
    
    ADD CONSTRAINT CHK_VALOR_ASOCIACIONES
    CHECK(VALOR>=0)
    
    ADD CONSTRAINT CHK_FRECUENCIA_ASOCIACIONES
    CHECK(FRECUENCIA IN ('QUINCENAL', 'MENSUAL'));
    
    
ALTER TABLE DEPOSITOSINVERSION
    ADD CONSTRAINT FK_ID_DEPOSITOSINVERSION
    FOREIGN KEY (ID) REFERENCES PRODUCTOS(ID)
     ON DELETE CASCADE;
    
    ALTER TABLE USUARIOSTIPOSOPERACION
    ADD CONSTRAINT FK_TIPOOPERACION_USUARIOSTIPOSOPERACION
    FOREIGN KEY (TIPOOPERACION) REFERENCES TIPOSOPERACION(TIPO);

ALTER TABLE USUARIOSTIPOSOPERACION
    ADD CONSTRAINT FK_USUARIO_USUARIOSTIPOSOPERACION
    FOREIGN KEY (USUARIO) REFERENCES USUARIOS(LOGIN);
    
    ALTER TABLE PUESTOSATENCIONTIPOSOPERACION
    ADD CONSTRAINT FK_TIPOOPERACION_PUESTOSATENCIONTIPOSOPERACION
    FOREIGN KEY (TIPOOPERACION) REFERENCES TIPOSOPERACION(TIPO);

ALTER TABLE PUESTOSATENCIONTIPOSOPERACION
    ADD CONSTRAINT FK_PUESTOATENCION_PUESTOSATENCIONTIPOSOPERACION
    FOREIGN KEY (PUESTOATENCION) REFERENCES PUESTOSDEATENCION(ID);
    
        
ALTER TABLE CLIENTESPRODUCTOS
    ADD CONSTRAINT FK_PRODUCTO_CLIENTESPRODUCTOS
    FOREIGN KEY (PRODUCTO) REFERENCES PRODUCTOS(ID);

ALTER TABLE CLIENTESPRODUCTOS
    ADD CONSTRAINT FK_CLIENTE_CLIENTESPRODUCTOS
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(LOGIN);
    
ALTER TABLE ASOCIACIONCUENTASEMPLEADOS
    ADD CONSTRAINT FK_ASOCIACION_ASOCIACIONCUENTASEMPLEADOS
    FOREIGN KEY (ASOCIACION) REFERENCES ASOCIACIONES(ID);

ALTER TABLE ASOCIACIONCUENTASEMPLEADOS
    ADD CONSTRAINT FK_CUENTAEMPLEADO_ASOCIACIONCUENTASEMPLEADOS
    FOREIGN KEY (CUENTAEMPLEADO) REFERENCES CUENTAS(ID);

    
commit;

